import { build } from "esbuild";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
const root = path.dirname(fileURLToPath(import.meta.url));
process.chdir(root);
await build({entryPoints:["entry.tsx"],outfile:"app.js",bundle:true,minify:true,platform:"browser",format:"iife",target:"es2020",jsx:"automatic",alias:{"@":root},define:{"process.env.NODE_ENV":'"production"'},legalComments:"eof"});
const result = await postcss([tailwind({base:root})]).process(await readFile("app/globals.css","utf8"),{from:path.join(root,"app/globals.css"),to:path.join(root,"styles.css")});
await writeFile("styles.css",result.css);
console.log("Built portable app.js and styles.css; index.html uses relative paths.");
